# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="nvim"

ZSH_THEME="spaceship"

SPACESHIP_DOCKER_SHOW=false
SPACESHIP_KUBECONTEXT_SYMBOL="  "
SPACESHIP_KUBECONTEXT_PREFIX="within"
SPACESHIP_CHAR_SYMBOL="  "

SPACESHIP_GIT_SYMBOL=" "
SPACESHIP_GIT_BRANCH_COLOR="red"

SPACESHIP_NODE_SYMBOL=" "

SPACESHIP_ELIXIR_SYMBOL=" "

plugins=(
  git
  docker
  zsh-syntax-highlighting
  history-substring-search
)

source $ZSH/oh-my-zsh.sh

alias v="nvim"


# This is something for git so that certain commands know what branch to go against
export REVIEW_BASE=master

export LC_ALL=en_US.UTF-8
