# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

export EDITOR="nvim"

ZSH_THEME="spaceship"

SPACESHIP_CHAR_SYMBOL="  "

SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_DIR_PREFIX=" "

SPACESHIP_GIT_BRANCH_COLOR="red"

SPACESHIP_VENV_PREFIX="in "

SPACESHIP_KUBECONTEXT_SYMBOL=" "
SPACESHIP_KUBECONTEXT_PREFIX="within"

SPACESHIP_NODE_SHOW=false
SPACESHIP_DOCKER_SHOW=false

plugins=(
  git
  docker
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

alias v="nvim"

# This is something for git so that certain commands know what branch to go against
export REVIEW_BASE=master

export LC_ALL=en_US.UTF-8
