export EDITOR="nvim"

alias v="nvim"

# This is something for git so that certain commands know what branch to go against
export REVIEW_BASE=master

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export STARSHIP_CONFIG=~/dotfiles/zsh/starship.toml
eval "$(starship init zsh)"
